backend:
  name: git-gateway
  branch: main

local_backend:
  url: http://localhost:54112/api/v1

media_folder: "public/images"
public_folder: "/images"

locale: "fr"

collections:
  - name: "collections"
    label: "Collections"
    files:
      - name: "meteore"
        label: "Collection Meteore"
        file: "public/content/meteore.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            field:
              name: "image"
              label: "Photo"
              widget: "image"

      - name: "reminescence"
        label: "Collection Reminescence"
        file: "public/content/reminescence.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            field:
              name: "image"
              label: "Photo"
              widget: "image"

      - name: "collab"
        label: "Collaborations"
        file: "public/content/collab.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            field:
              name: "image"
              label: "Photo"
              widget: "image"

      - name: "placidite"
        label: "Collection Placidite"
        file: "public/content/placidite.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            field:
              name: "image"
              label: "Photo"
              widget: "image"

      - name: "contraste"
        label: "Contraste & Mouvement"
        file: "public/content/contraste.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            field:
              name: "image"
              label: "Photo"
              widget: "image"

      - name: "homepage"
        label: "Photos Accueil"
        file: "public/content/homepage.json"
        fields:
          - name: "images"
            label: "Photos"
            widget: "list"
            fields:
              - name: "image"
                label: "Photo"
                widget: "image"
              - name: "link"
                label: "Lien vers collection"
                widget: "select"
                options:
                  - { label: "Meteore", value: "/collection/meteore" }
                  - { label: "Reminescence", value: "/collection/reminescence" }
                  - { label: "Placidite", value: "/collection/placidite" }
                  - { label: "Contraste & Mouvement", value: "/collection/contraste" }
                  - { label: "Collaborations", value: "/collection/collab" }
